export enum GenreMusic {
  ROCK = 'rock',
  HARD_ROCK = 'hard_rock',
  ALTERNATIVE_ROCK = 'alternative_rock',
  GARAGE_ROCK = 'garage_rock',
  GRUNGE = 'grunge',
  PROGRESSIVE_ROCK = 'progressive_rock',
  POST_ROCK = 'post_rock',
  PUNK = 'punk',
  PUNK_HARDCORE = 'punk_hardcore',
  POST_PUNK = 'post_punk',
  METAL = 'metal',
  HEAVY_METAL = 'heavy_metal',
  THRASH_METAL = 'thrash_metal',
  DEATH_METAL = 'death_metal',
  BLACK_METAL = 'black_metal',
  DOOM_METAL = 'doom_metal',
  SLUDGE_METAL = 'sludge_metal',
  STONER_METAL = 'stoner_metal',
  PROGRESSIVE_METAL = 'progressive_metal',
  METALCORE = 'metalcore',
  DEATHCORE = 'deathcore',
  NU_METAL = 'nu_metal',
  INDUSTRIAL_METAL = 'industrial_metal',
  HEAVY_BLUES = 'heavy_blues',
  OTHER = 'other',
}